config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jenkins-docs/simple-java-maven-app:
      branch: master
      repo: https://github.com/jenkins-docs/simple-java-maven-app
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Lic:
    repos:
      github.com/jenkins-docs/simple-java-maven-app:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-taupe-reindeer.sh
        container: qc.lic_boozy-smalt-maltese
timeout: 600
